Traceback (most recent call last):
  File "/work/u5066474/NTHU/test2.py", line 21, in <module>
    df = pd.read_csv('../../data/unique_ligands_processed.csv', nrows=50)
  File "/work/u5066474/NTHU/.ven/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/work/u5066474/NTHU/.ven/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/work/u5066474/NTHU/.ven/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/work/u5066474/NTHU/.ven/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/work/u5066474/NTHU/.ven/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../../data/unique_ligands_processed.csv'
